/* This file was generated by SableCC (http://www.sablecc.org/). */

package cours6.syntax.node;

import cours6.syntax.analysis.*;

@SuppressWarnings("nls")
public final class AModExp extends PExp
{
    private PExp _left_;
    private TModulo _modulo_;
    private PTerm _right_;

    public AModExp()
    {
        // Constructor
    }

    public AModExp(
        @SuppressWarnings("hiding") PExp _left_,
        @SuppressWarnings("hiding") TModulo _modulo_,
        @SuppressWarnings("hiding") PTerm _right_)
    {
        // Constructor
        setLeft(_left_);

        setModulo(_modulo_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AModExp(
            cloneNode(this._left_),
            cloneNode(this._modulo_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModExp(this);
    }

    public PExp getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExp node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TModulo getModulo()
    {
        return this._modulo_;
    }

    public void setModulo(TModulo node)
    {
        if(this._modulo_ != null)
        {
            this._modulo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._modulo_ = node;
    }

    public PTerm getRight()
    {
        return this._right_;
    }

    public void setRight(PTerm node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._modulo_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._modulo_ == child)
        {
            this._modulo_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PExp) newChild);
            return;
        }

        if(this._modulo_ == oldChild)
        {
            setModulo((TModulo) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
