/* This file was generated by SableCC (http://www.sablecc.org/). */

package cours6.syntax.node;

import cours6.syntax.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleFactor extends PFactor
{
    private PSign _sign_;

    public ASimpleFactor()
    {
        // Constructor
    }

    public ASimpleFactor(
        @SuppressWarnings("hiding") PSign _sign_)
    {
        // Constructor
        setSign(_sign_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleFactor(
            cloneNode(this._sign_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleFactor(this);
    }

    public PSign getSign()
    {
        return this._sign_;
    }

    public void setSign(PSign node)
    {
        if(this._sign_ != null)
        {
            this._sign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sign_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sign_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sign_ == child)
        {
            this._sign_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sign_ == oldChild)
        {
            setSign((PSign) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
