/* This file was generated by SableCC (http://www.sablecc.org/). */

package cours6.syntax.parser;

import cours6.syntax.node.*;
import cours6.syntax.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 0;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 1;
    }

    @Override
    public void caseTStar(@SuppressWarnings("unused") TStar node)
    {
        this.index = 2;
    }

    @Override
    public void caseTSlash(@SuppressWarnings("unused") TSlash node)
    {
        this.index = 3;
    }

    @Override
<<<<<<< HEAD
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
=======
    public void caseTModulo(@SuppressWarnings("unused") TModulo node)
>>>>>>> a3f0b03 (.)
    {
        this.index = 4;
    }

    @Override
<<<<<<< HEAD
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
=======
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
>>>>>>> a3f0b03 (.)
    {
        this.index = 5;
    }

    @Override
<<<<<<< HEAD
    public void caseTNum(@SuppressWarnings("unused") TNum node)
=======
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
>>>>>>> a3f0b03 (.)
    {
        this.index = 6;
    }

    @Override
<<<<<<< HEAD
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 7;
    }
=======
    public void caseTNum(@SuppressWarnings("unused") TNum node)
    {
        this.index = 7;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 8;
    }
>>>>>>> a3f0b03 (.)
}
