/* This file was generated by SableCC (http://www.sablecc.org/). */

package cours6.syntax.analysis;

import cours6.syntax.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAAddExp(AAddExp node);
    void caseASubExp(ASubExp node);
    void caseASimpleExp(ASimpleExp node);
    void caseAMultFactor(AMultFactor node);
    void caseADivFactor(ADivFactor node);
    void caseAModFactor(AModFactor node);
    void caseASimpleFactor(ASimpleFactor node);
    void caseAPosSign(APosSign node);
    void caseANegSign(ANegSign node);
    void caseASimpleSign(ASimpleSign node);
    void caseANumTerm(ANumTerm node);
    void caseAParTerm(AParTerm node);

    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTStar(TStar node);
    void caseTSlash(TSlash node);
    void caseTPercent(TPercent node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTNum(TNum node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
